### PR TITLE
Add PikaPods managed hosting option

### PR DESCRIPTION
**Pull request by m3nu**
As discussed on Discord. Adds page for managed hosting options and PikaPods.

[Preview](https://github.com/m3nu/Wiki/blob/add-pikapods/pages/02.install/11.managed-hosting/default.en.md)

### CODE REVIEW

**Comment by majora2007** [comment]
I think it might be nice to add a note about revenue share back, which is a big bonus in supporting Open Source and if there are ever more hosted servers, would help sway users to your services.

**Comment by m3nu** [comment]
Agreed. Already updated.

**Comment by m3nu** [comment]
Hey, saw that SVGs aren't really supported and you added a PNG. That works too. Thanks for fixing!

**Comment by majora2007** [comment]
Yeah, but having some trouble with the markup to get it to link correctly. I'll work on it this morning to get it linked out correctly or adjust with a dedicated link if all else fails.

**Comment by majora2007** [comment]
If you wouldn't mind raising another PR with a higher res image (PNG) of your Run on PikaPods, I think that would look much better.

**Comment by m3nu** [comment]
Sure thing. Was already considering it.

**Pull request merged**
