### PR TITLE
Higher-res PikaPods button

### PR DESCRIPTION
**Pull request by m3nu**
Added a high-res PNG, if you want to use it. Actually without it works just as well. The button is more for use in READMEs. So never mind.

If you do want to use it, I'm not sure on the path to use. But it would be like this:

``

(since Markdown doesn't support setting a width)

### CODE REVIEW

**Comment by m3nu** [comment]
Hey @majora2007, bumping this PR to add a better image (or remove it) in case it got overlooked. 😀

**Comment by majora2007** [comment]
Definitely didn't forget, just out of town on holiday at the minute. I will review and merge once I'm back.

**Comment by therobbiedavis** [comment]
@m3nu Can you supply either the image itself or a url to the image? Our wiki system, Grav, should be able to handle absolute urls along with relative, but just in case we need to upload it locally we need the file.

**Comment by ThePromidius** [comment]
Last PR we had issues with the link crashing the wiki page so we did have to manually upload the image iirc. So as Robbie mentioned it'd be required.

**Comment by m3nu** [comment]
Yeah, I saw the error messages for a few minutes. Probably it doesn't like SVGs. Pushed a change with a scaled external PNG image instead. Looks like this when rendered on Github:

https://github.com/m3nu/Wiki/blob/pikapods-highres/pages/02.install/11.managed-hosting/default.en.md

**Review by majora2007 — APPROVED** [review]

**Pull request merged**
